
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 14 19:52:36 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 10;
  public static final int SEMICOLON = 24;
  public static final int OR = 9;
  public static final int INT = 3;
  public static final int EQUAL = 13;
  public static final int NOTEQUAL = 19;
  public static final int CHAR = 4;
  public static final int LEFTPAR = 22;
  public static final int LOOP = 7;
  public static final int RIGHTCURLYPAR = 26;
  public static final int GREATER = 20;
  public static final int INTCONST = 15;
  public static final int RIGHTPAR = 23;
  public static final int LOWEROREQUAL = 12;
  public static final int ID = 18;
  public static final int COMMA = 27;
  public static final int LEFTCURLYPAR = 25;
  public static final int LOWER = 11;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int GREATEROREQUAL = 21;
  public static final int CHARCONST = 17;
  public static final int MAIN = 2;
  public static final int error = 1;
  public static final int ASSIGN = 28;
  public static final int BOOL = 6;
  public static final int REDO = 8;
  public static final int FLOATCONST = 16;
  public static final int BOOLCONST = 14;
}

