
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 12 20:55:16 CET 2023
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 10;
  public static final int SEMICOLON = 19;
  public static final int OR = 9;
  public static final int INT = 3;
  public static final int EQUAL = 13;
  public static final int CHAR = 4;
  public static final int NOTEQUAL = 14;
  public static final int LEFTPAR = 17;
  public static final int LOOP = 7;
  public static final int RIGHTCURLYPAR = 21;
  public static final int GREATER = 15;
  public static final int INTCONST = 25;
  public static final int RIGHTPAR = 18;
  public static final int LOWEROREQUAL = 12;
  public static final int ID = 24;
  public static final int COMMA = 22;
  public static final int LEFTCURLYPAR = 20;
  public static final int LOWER = 11;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int GREATEROREQUAL = 16;
  public static final int CHARCONST = 27;
  public static final int MAIN = 2;
  public static final int error = 1;
  public static final int ASSIGN = 23;
  public static final int BOOL = 6;
  public static final int REDO = 8;
  public static final int FLOATCONST = 26;
  public static final int BOOLCONST = 28;
}

